version: '3.1'
services:
  redis-stack:
    image: redis/redis-stack-server:7.2.0-v6
    restart: always
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PWD} --dir ${REDIS_DATA_DIR} --loadmodule /opt/redis-stack/lib/redisearch.so --loadmodule /opt/redis-stack/lib/rejson.so"
    environment:
      # Persist after 1hr if 1 write, after 5min if 100 writes, after 60 sec if 10000 writes
      - REDIS_ARGS=--save 3600 1 --save 300 100 --save 60 10000
    ports:
      - 6379:6379
    volumes:
      - redisData:${REDIS_DATA_DIR}
    env_file:
      - .env.dev

volumes:
  redisData:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/Dev/volumes/redisData
