# Base image
FROM python:3.11.4-slim-buster

# set work directory
WORKDIR /usr/image_search/api

# set environment variables
# PYTHONDONTWRITEBYTECODE: Prevents Python from writing pyc files to disc (equivalent to python -B option)
# PYTHONUNBUFFERED: Prevents Python from buffering stdout and stderr (equivalent to python -u option)
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies
RUN pip install --upgrade pip
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

# copy project source code
COPY ./src /usr/image_search/api/

# run entrypoint.sh
# ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
